# -*- coding: utf-8 -*-
"""Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWTf_vegEdX8SJfyXyagujVliK7nwjc4

## Training image classificatiion model using yolo
"""

!nvidia-smi

!unzip /content/data.zip

!pip install ultralytics==8.2.103 -q

!yolo settings sync=False
from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
!yolo task=classify mode=train model=yolov8n-cls.pt data=/content/data.zip epochs=25  imgsz=128

"""## Sample Prediction"""

!yolo task=classify mode=predict model=/content/runs/classify/train/weights/best.pt conf=0. source=/content/test/images

import glob

from IPython.display import Image, display

for image_path in glob.glob('/content/runs/classify/predict/*.jpg')[:3]:
  display(Image(filename=image_path, width=600))
  print("\n")